services:
  ao-analytics-api:
    container_name: ao-analytics-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - ao-analytics-db
    ports:
      - "8080:8080"