services:
  aodata-api:
    container_name: aodata-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - aodata-db
    ports:
      - "8080:8080"